apiVersion: apps/v1
kind: Deployment
metadata:
  name: test23
  labels:
    app: test23
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717751054721
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test23
  template:
    metadata:
      labels:
        app: test23
    spec:
      containers:
        - name: test23
          image: acrworkflow1717751054721.azurecr.io/image-workflow-1717751054721:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
