apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: petstore
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: petstore
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002