apiVersion: v1
kind: Service
metadata:
  name: test23
  namespace: namespace-workflow-1717751054721
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: test23
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000